// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecodeMvc.Models;

namespace RecodeMvc.Migrations.SqlServerMigrations
{
    [DbContext(typeof(PromocaoContext))]
    [Migration("20211213060123_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecodeMvc.Models.Promocao", b =>
                {
                    b.Property<int>("Id_Promo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Destino_Promo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qntd_Dias")
                        .HasColumnType("int");

                    b.Property<float>("Valor_promo")
                        .HasColumnType("real");

                    b.HasKey("Id_Promo");

                    b.ToTable("Promocaos");
                });
#pragma warning restore 612, 618
        }
    }
}
